### ISSUE TITLE
Plants aren't showing the right stage of growth

### ISSUE THREAD

**Issue by Syndlig** [nictuku/stardew-rocks#10]
how plants looks in stardew.rocks: http://i.imgur.com/hsznPKW.png
how they are in-game: http://i.imgur.com/YbfdXDQ.jpg

some crops are showing as a later stage than they actually are

**Comment by nictuku** [comment]
Apparently this is fixed now, right @Syndlig  ?

**Comment by nictuku** [comment]
Syndlig confirms this is good now.
