### ISSUE TITLE
web/client: discord widget

### ISSUE THREAD

**Issue by nictuku** [nictuku/stardew-rocks#21]
It would be nice to have a place for people to go to and talk about their farms.

I created a channel on our discord, people maybe could use that.

JSON endpoint address:
`https://discordapp.com/api/servers/161199619630563329/widget.json`

Widget:
`
<iframe src="https://discordapp.com/widget?id=161199619630563329&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0"></iframe>
`

**Comment by gumbyscout** [comment]
I'm not actually sure where we'd put a widget like this. I think having the discord server somewhere would be good for using as a 'support' sorta thing, but I need suggestions on where to actually put something that shows server status. I'm thinking of maybe making a drawer on the website and putting it in it? What are your thoughts?

**Comment by nictuku** [comment]
I have a really bad intuition for these things. That said, my thought is: a simple static button in the top bar, like the other ones. Then at the bottom of the index we can add the server stats.

But I think that's a bad thought, heh.

I believe we need a more scalable design that can grow to have more links and information. So a drawer might be a better idea, because we can add more items there as our needs evolve.

(later we should probably move the donate button to somewhere inside the drawer, then replace it with login/sign up stuff)

**Comment by gumbyscout** [comment]
Yeah, I think a static button to the channel in the navbar, and then stats in the footer might work for now.

**Comment by gumbyscout** [comment]
Hopefully I did everything we needed in #41
