### ISSUE TITLE
web/client: paypal donate button

### ISSUE THREAD

**Issue by nictuku** [nictuku/stardew-rocks#22]
It seems like people want our help relieving themselves of their hard-earned money. Here's a widget for paypal button:

https://gist.github.com/nictuku/ab039ab3ea3f4b79b131

**Comment by gumbyscout** [comment]
a0d305ee878908893686dcb18ddfcdc3cf963684 should add the paypal button

**Comment by nictuku** [comment]
fwiw I really like the style you picked
