### ISSUE TITLE
web/server: not serving JS consistently after version changes

### ISSUE THREAD

**Issue by nictuku** [nictuku/stardew-rocks#32]
I believe one of the reasons we failed in our attempt to use a CDN is that our js files are not versioned.

People's browsers and the CDN can cache the JS file. If we make a change to the JS, it should use a new file name to ensure the new file is not cached.

So index.html should make references to a hashed or versioned file, and we should be able to serve that appropriately.

All of this can be solved server-side without the client code knowing about it. Example implementation:
https://github.com/pagespeed/mod_pagespeed or ngx_pagespeed.

It may be time for us to retire our non-API Go server. (keep the API server, moving the routing bits to nginx/apache)

**Comment by gumbyscout** [comment]
So separate the server that serves the web app, and the api? We'll have to make sure that we add proper CORS headers to the api server when we do that.

**Comment by nictuku** [comment]
They could be in the same origin. nginx could route /api/ requests to the Go server. Right?

**Comment by gumbyscout** [comment]
Or you could have api be a subdomain? Like api.stardew.farm?

**Comment by nictuku** [comment]
Or that

**Comment by nictuku** [comment]
I setup an apache2 server in front of the Go one, with the goal of using mod_pagespeed and doing other optimizations. For now it will simply proxy everything to the Go server but I'll move the routing to the apache server soon.

(I used apache rather than nginx because it was a lot more convenient to use with mod_pagespeed rather than the nginx one).

FWIW, mod_pagespeed was not able to consolidate and version our javascripts - so it didn't change their URL and therefore our JS/CSS are still CDN unfriendly. So this bug remains very much open.

**Comment by nictuku** [comment]
Changes to make assets versioned:
```

$ diff -u index.html index2.html 
--- index.html  2016-03-27 01:15:39.092000000 -0400
+++ index2.html 2016-03-27 19:44:36.412000000 -0400
@@ -25,12 +25,12 @@
   </head>
   <body>
     <div id="app"></div>
-    <script src="jspm_packages/system.js"></script>
-    <script src="jspm.browser.js"></script>
-    <script src="jspm.config.js"></script>
-    <script src="build.js"></script>
+    <script src="assets/1459122195/jspm_packages/system.js"></script>
+    <script src="assets/1459122195/jspm.browser.js"></script>
+    <script src="assets/1459122195/jspm.config.js"></script>
+    <script src="assets/1459122195/build.js"></script>
     <script>
-      System.import('src/main.js');
+      System.import('assets/1459122195/src/main.js');
     </script>
   </body>
 </html>

```

```
:~/www/assets/1459122195$ grep 1459122195 * -R
jspm.browser.js:    "github:*": "assets/1459122195/jspm_packages/github/*",
jspm.browser.js:    "npm:*": "assets/1459122195/jspm_packages/npm/*",
jspm.browser.js:    "stardew-rocks-web-client/": "assets/1459122195/src/"
```

**Comment by nictuku** [comment]
@gumbyscout 

While I could use some scripting to inject the different asset directory in the sources, I'd like to make the deploy scripts simple and reliable, with less weird logic in them.

Can we add a "SDFROOT" token in the source files, so it's trivial to find where the asset directory should be replaced? Or do you have a better suggestion?

**Comment by nictuku** [comment]
```
sed -e 's|src="|src="assets/1459135492/|' -e 's|src/main|assets/1459135492/src/main|' -i *html

sed -e 's|baseURL: "/"|baseURL: "/assets/1459135492/"|' jspm.browser.js
```

**Comment by nictuku** [comment]
as root
```
sed -e 's/DirectoryIndex index.*.html/DirectoryIndex index1459137641.html/' /etc/apache2/sites-enabled/000-default.conf
```

**Comment by nictuku** [comment]
web/client/deploy.sh now does the right thing.

#35 is still open about pending optimizations (e.g: set expiration date to a high value)
